{
 "title": "BookStore dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Orders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Orders Placed",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(total_orders_Orders)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total Orders Placed by City",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "total_orders_Orders", "legendFormat": "{{City}}" }
     ]
    },
    {
     "title": "Orders Canceled",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "orders_canceled", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Avg. Order Price",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "orders_price_Euros_sum / orders_price_Euros_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg. Number of Books per Order",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "orders_number_of_books_Books_sum / orders_number_of_books_Books_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of books per order",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "orders_number_of_books_Books_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Price Distribution per Order",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "orders_price_Euros_bucket", "legendFormat": "{{le}}" }
     ]
    }
   ]
  },
  {
   "title": "Books",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number of Books Available in the Store",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "total_books", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Books Added",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 5, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "books_added_Book", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Books Deleted",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 9, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "books_deleted_Book", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Books Updated",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 13, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "books_updated_Book", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Categories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number of Categories Available in the Store",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "total_categories", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Categories Added",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "categories_added_Category", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Categories Updated",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 9, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "categories_updated_Category", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Categories Deleted",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 13, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "categories_deleted_Category", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}