{
 "title": "Http Requests",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Avg response times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Http Response times",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 21, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_ms_sum[$__rate_interval])) / sum(rate(http_server_duration_ms_count[$__rate_interval]))",
       "legendFormat": "response time"
      }
     ]
    }
   ]
  },
  {
   "title": "Number of requests per controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of requests per endpoint and verb at the CategoriesController",
     "type": "stat",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_server_duration_ms_count{http_target=\"api/Categories/{id:int}\"}",
       "legendFormat": "{{http_status_code}} {{http_target}} {{http_method}}"
      },
      {
       "expr": "http_server_duration_ms_count{http_target=\"api/Categories\"}",
       "legendFormat": "{{http_status_code}} {{http_target}} {{http_method}}"
      }
     ]
    },
    {
     "title": "Number of requests per endpoint and verb at the BooksController",
     "type": "stat",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_server_duration_ms_count{http_target=\"api/Books/{id:int}\"}",
       "legendFormat": "{{http_status_code}} {{http_target}} {{http_method}}"
      },
      {
       "expr": "http_server_duration_ms_count{http_target=\"api/Books\"}",
       "legendFormat": "{{http_status_code}} {{http_target}} {{http_method}}"
      }
     ]
    },
    {
     "title": "Number of requests per endpoint and verb at the InventoriesController",
     "type": "stat",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_server_duration_ms_count{http_target=\"api/Inventories\"}",
       "legendFormat": "{{http_status_code}} {{http_target}} {{http_method}}"
      },
      {
       "expr": "http_server_duration_ms_count{http_target=\"api/Inventories/get-inventory-by-book-name/{bookName}\"}",
       "legendFormat": "{{http_status_code}} {{http_target}} {{http_method}}"
      },
      {
       "expr": "http_server_duration_ms_count{http_target=\"api/Inventories/{bookId:int}\"}",
       "legendFormat": "{{http_status_code}} {{http_target}} {{http_method}}"
      }
     ]
    },
    {
     "title": "Number of requests per endpoint and verb at the OrdersController",
     "type": "stat",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_server_duration_ms_count{http_target=\"api/Orders/{id:int}\"}",
       "legendFormat": "{{http_status_code}} {{http_target}} {{http_method}}"
      },
      {
       "expr": "http_server_duration_ms_count{http_target=\"api/Orders\"}",
       "legendFormat": "{{http_status_code}} {{http_target}} {{http_method}}"
      }
     ]
    }
   ]
  }
 ]
}